### ISSUE TITLE
AttributeError: 'Editor' object has no attribute 'opt'

### ISSUE THREAD

**Issue by chuan19** [e4s2022/e4s#16]
(e4s) root@autodl-container-fe7811a13c-a73d6848:~/autodl-tmp/FinegrainedFace/e4s# python face_edit.py --source=./example/input/faceedit/source.jpg --reference=./example/input/faceedit/reference.jpg --region hair eyes  --alpha=1
Traceback (most recent call last):
  File "face_edit.py", line 107, in <module>
    editor = Editor(opts)
  File "face_edit.py", line 34, in __init__
    self.faceParsing_model = init_faceParsing_pretrained_model(self.opts.faceParser_name, self.opt.faceParsing_ckpt, self.opt.segnext_config)
AttributeError: 'Editor' object has no attribute 'opt'

**Comment by colt18** [comment]
Change `opt` to `opts` on line 34:        

> self.faceParsing_model = init_faceParsing_pretrained_model(self.opts.faceParser_name, self.opts.faceParsing_ckpt, self.opts.segnext_config)
