### ISSUE TITLE
checkpoint

### ISSUE THREAD

**Issue by postcw** [e4s2022/e4s#6]
The training process encountered No such file or directory: './pretrained_ckpts/auxiliray/model.pth' This checkpoint does not seem to be mentioned?

**Comment by e4s2022** [comment]
Could you please post the command line output information?

**Comment by postcw** [comment]
Traceback (most recent call last):
  File "scripts/train.py", line 30, in <module>
    main()
  File "scripts/train.py", line 25, in main
    coach = Coach(opts)
  File "/root/data/practice/e4s-main/src/training/coach.py", line 152, in __init__
    self.face_parsing_loss = FaceParsingLoss(self.opts).to(self.device).eval()
  File "/root/data/practice/e4s-main/src/criteria/face_parsing/face_parsing_loss.py", line 29, in __init__
    self.G.load_state_dict(torch.load(opts.face_parsing_model_path))
  File "/root/anaconda3/envs/e4s/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/anaconda3/envs/e4s/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/anaconda3/envs/e4s/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './pretrained_ckpts/auxiliray/model.pth'

**Comment by e4s2022** [comment]
Indeed, the `./pretrained_ckpts/auxiliray/model.pth` was ignored by the `.gitignore` file due to an incorrectly configured rule. I've added it to the main branch, please check the latest update.  

Thank you for pointing out this bit.

**Comment by qqpann** [comment]
@e4s2022 Hi, I think model_ir_se50.pth is also missing. How can i get it?

**Comment by aprillysea** [comment]
can not load fetch_gpen_models.sh,how can i get it
