### ISSUE TITLE
Can we run face swap with CPU and without GPU?

### ISSUE THREAD

**Issue by arnold408** [e4s2022/e4s#7]
Hello,
I got this error : when I tried face swap.

Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/root/e4s/scripts/face_swap.py", line 17, in <module>
    from src.pretrained.face_parsing.face_parsing_demo import init_faceParsing_p                                                                                        retrained_model, faceParsing_demo, vis_parsing_maps
  File "/root/e4s/src/pretrained/face_parsing/face_parsing_demo.py", line 13, in                                                                                         <module>
    from src.pretrained.face_parsing.model import BiSeNet, seg_mean, seg_std
  File "/root/e4s/src/pretrained/face_parsing/model.py", line 15, in <module>
    seg_mean = torch.from_numpy(np.array([[0.485, 0.456, 0.406]])).float().cuda(                                                                                        ).reshape(1,3,1,1)
  File "/usr/local/lib64/python3.9/site-packages/torch/cuda/__init__.py", line 2                                                                                        47, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have                                                                                         an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.a                                                                                        spx

Please suggest if this can be used with CPU instead of GPU. 
Thanks.

**Comment by e4s2022** [comment]
Didn't test with full CPU env, which is not recommended

**Comment by arnold408** [comment]
Please test with CPU only linux server and tell me if e4s will work or not. Thanks
